const rules = console.log(
  "\n",
  "*********** Clean Code Rules ***********",
  "\n",
  "\n",
  "1.Don't say I will back to fix it later",
  "\n",
  "2.Always leave the campground cleaner than you found it.",
  "\n",
  "3.The name of a variable, function or class, should answer all the big questions.",
  "\n",
  "4.Firstly, functions should be small, secondly functions should be smaller than that.",
  "\n",
  "5.Nothing can be quite so helpful as a well-placed comment.",
  "\n",
  "6.Code formatting is important. It is too important to ignore.",
  "\n",
  "7.Always make place for error handling.",
  "\n",
  "8.Set boundaries,  and  be careful when you user third party code.",
  "\n",
  "9.Don't ignore writing test, its the real shortcut.",
  "\n",
  "10.Classes should be small, with single responsibility principle",
  "\n",
  "11.Software Systems should separate the startuo process",
  "\n"
)
module.exports = { rules }